version: '2.0'

services:
  fr24feed:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
    container_name: fr24feed
    restart: always
    ports:
      - 8754:8754
    environment:
      - BEASTHOST=192.168.2.9
      - FR24KEY=${FR24_KEY}
    dns_search: .
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8754 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
