version: '2.0'

services:
  fr24feed:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
    container_name: fr24feed
    restart: always
    ports:
      - 8754:8754
    environment:
      - BEASTHOST=192.168.2.9
      - FR24KEY=${FR24_KEY}
    dns_search: .
    labels:
      - homepage.group=Docker
      - homepage.name=FlightRadar24
      - homepage.icon=mdi-airplane
      - homepage.href=http://192.168.2.9:8754
      - homepage.description=Flight Tracking Feeder
      - homepage.weight=100
      - homepage.server=raspi5
      - homepage.container=fr24feed
      - homepage.widget.type=docker
