version: "3"
services:
  tado_aa:
    restart: always
    container_name: tado_aa
    image: saschabrockel/tado_aa:latest
    environment:
      - GEOFENCING=True
      - OPENWINDOWDETECTION=True
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f tado_aa || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
