version: '2'
services:
  homebridge:
    image: nebu2k/homebridge-custom:latest
    restart: always
    network_mode: host
    labels:
      - homepage.group=Applications
      - homepage.name=Homebridge (Pi5)
      - homepage.description=HomeKit Bridge
      - homepage.icon=homebridge.png
      - homepage.href=http://192.168.2.9:8581
      - homepage.weight=30
      - homepage.widget.type=homebridge
      - homepage.widget.url=http://192.168.2.9:8581
      - homepage.widget.username=${HOMEBRIDGE_USERNAME}
      - homepage.widget.password=${HOMEBRIDGE_PASSWORD}
    volumes:
      - /data/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
