services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /data/beszel/beszel_data:/beszel_data
      - /data/beszel/beszel_socket:/beszel_socket
    labels:
      homepage.group: Monitoring
      homepage.name: Beszel
      homepage.icon: beszel.png
      homepage.href: https://beszel.elmstreet79.de
      homepage.description: System Monitor
      homepage.weight: 40
      homepage.widget.type: beszel
      homepage.widget.url: https://beszel.elmstreet79.de
      homepage.widget.username: ${BESZEL_USERNAME}
      homepage.widget.password: ${BESZEL_PASSWORD}
      homepage.widget.version: 2

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: '${BESZEL_KEY}'
