services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    labels:
      - homepage.group=Docker
      - homepage.name=Beszel (Pi5)
      - homepage.description=System Monitor
      - homepage.icon=beszel.png
      - homepage.href=http://192.168.2.9
      - homepage.weight=20
      - homepage.widget.type=docker
    ports:
      - 8090:8090
    volumes:
      - /data/beszel/beszel_data:/beszel_data
      - /data/beszel/beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: '${BESZEL_KEY}'
    healthcheck:
      test: ["CMD-SHELL", "test -S /beszel_socket/beszel.sock || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s