services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /data/beszel/beszel_data:/beszel_data
      - /data/beszel/beszel_socket:/beszel_socket
    labels:
      homepage.group: Monitoring
      homepage.name: Beszel (Pi5)
      homepage.icon: beszel.png
      homepage.href: http://beszel.elmstreet79.de
      homepage.description: System Monitor
      homepage.weight: 20
      homepage.widget.type: beszel
      homepage.widget.url: http://beszel.elmstreet79.de
      homepage.widget.username: "{{HOMEPAGE_VAR_BESZEL_USER}}"
      homepage.widget.password: "{{HOMEPAGE_VAR_BESZEL_PASS}}"
      homepage.widget.version: 2

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: '${BESZEL_KEY}'
    healthcheck:
      test: ["CMD-SHELL", "test -S /beszel_socket/beszel.sock || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s