version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=MinIO
      - homepage.description=S3 Storage
      - homepage.icon=minio.png
      - homepage.href=http://minio.elmstreet79.de
      - homepage.weight=60
    ports:
      - "9300:9000"
      - "9393:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - /media/share/minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
